# Generated by Django 4.1.7 on 2023-03-28 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxes',
            name='addressfrom',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='boxes',
            name='addressto',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='boxes',
            name='boximg',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='boxes',
            name='clientfrom',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='boxes',
            name='clientto',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='boxes',
            name='regionfrom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='A_region', to='boxes.region'),
        ),
        migrations.AlterField(
            model_name='boxes',
            name='regionto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='B_region', to='boxes.region'),
        ),
        migrations.AlterField(
            model_name='boxes',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
