# Generated by Django 4.1.7 on 2023-11-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='room',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='status',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='type',
        ),
        migrations.AddField(
            model_name='feedback',
            name='answerdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
