# Generated by Django 4.1.7 on 2023-04-01 10:32

import boxes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0004_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxes',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='boxes',
            name='valuta',
            field=models.CharField(choices=[('TMT', 'Manat'), ('USD', 'Dollar')], default='tmt', max_length=25),
        ),
        migrations.AlterField(
            model_name='boxes',
            name='boximg',
            field=models.ImageField(blank=True, upload_to=boxes.models.set_image_name),
        ),
        migrations.AlterField(
            model_name='boxes',
            name='phoneto',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
