# Generated by Django 4.1.7 on 2023-04-03 08:11

import boxes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0005_boxes_amount_boxes_valuta_alter_boxes_boximg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxes',
            name='boximg',
            field=models.ImageField(blank=True, default='images/emptybox.png', upload_to=boxes.models.set_image_name),
        ),
    ]
