# Generated by Django 4.1.7 on 2023-04-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0006_alter_boxes_boximg'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxes',
            name='placecount',
            field=models.IntegerField(default=0),
        ),
    ]
