# Generated by Django 4.1.7 on 2023-04-03 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0007_boxes_placecount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputdate', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='called', max_length=25)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxes.boxes', verbose_name='Boxes')),
            ],
        ),
    ]
