# Generated by Django 4.1.7 on 2023-04-03 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boxes', '0008_boxhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxhistory',
            name='regionbh',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boxhistory',
            name='userfrom',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='UserFrom', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boxhistory',
            name='userto',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='UserTo', to=settings.AUTH_USER_MODEL),
        ),
    ]
