# Generated by Django 4.1.7 on 2023-04-03 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0009_boxhistory_regionbh_boxhistory_userfrom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxhistory',
            name='regionbh',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='boxes.region', verbose_name='RegionHB'),
        ),
    ]
