# Generated by Django 4.1.7 on 2023-04-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0010_alter_boxhistory_regionbh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxhistory',
            name='status',
            field=models.CharField(choices=[('create', 'Create'), ('called', 'Called'), ('approved', 'Approved'), ('accepted', 'Accepted'), ('sent', 'Sent'), ('rejected', 'Rejected'), ('canceled', 'Canceled'), ('closed', 'Closed')], default='called', max_length=25),
        ),
    ]
