# Generated by Django 4.1.7 on 2023-04-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0011_alter_boxhistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='tarif',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
