# Generated by Django 4.1.7 on 2023-04-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0012_region_tarif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='type_region',
            field=models.CharField(choices=[('AG', 'Aşgabat'), ('AH', 'Ahal'), ('BN', 'Balkan'), ('MR', 'Mary'), ('LB', 'Lebap'), ('DZ', 'Daşoguz')], max_length=10, verbose_name='Region district'),
        ),
    ]
