# Generated by Django 4.1.7 on 2023-04-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0014_alter_region_hi_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='hi_region',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
