# Generated by Django 4.1.7 on 2023-04-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0016_remove_region_type_region_alter_region_hi_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='hi_region',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
