# Generated by Django 4.1.7 on 2023-05-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0017_alter_region_hi_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxes',
            name='updatedate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='boxes',
            name='inputdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
