# Generated by Django 4.1.7 on 2023-05-03 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0018_boxes_updatedate_alter_boxes_inputdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxes',
            name='inputdate',
        ),
    ]
