# Generated by Django 4.1.7 on 2023-05-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0020_boxes_inputdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='hi_region',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
    ]
