# Generated by Django 4.2 on 2023-05-08 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0021_alter_region_hi_region'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
