# Generated by Django 4.1.7 on 2023-03-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_cuser_type_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='type_user',
            field=models.CharField(choices=[('driver', 'Driver'), ('manager', 'Manager'), ('admin', 'Admin'), ('client', 'Client')], default='client', max_length=10),
        ),
    ]
