# Generated by Django 4.1.7 on 2023-12-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_cuser_type_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='datefrom',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='dateto',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
