# Generated by Django 4.1.7 on 2023-04-01 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0005_boxes_amount_boxes_valuta_alter_boxes_boximg_and_more'),
        ('users', '0003_alter_cuser_type_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='boxes.region'),
        ),
    ]
