# Generated by Django 4.1.7 on 2023-12-11 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_alter_cuser_datefrom_alter_cuser_dateto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
