# Generated by Django 4.1.7 on 2023-04-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_cuser_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='inputdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
