# Generated by Django 4.1.7 on 2023-05-04 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_cuser_inputdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='datefrom',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 20, 59, 20, 702944)),
        ),
        migrations.AddField(
            model_name='cuser',
            name='dateto',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 20, 59, 20, 702944)),
        ),
    ]
