# Generated by Django 4.1.7 on 2023-05-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_cuser_datefrom_cuser_dateto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='datefrom',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='dateto',
            field=models.DateTimeField(blank=True),
        ),
    ]
