# Generated by Django 4.1.7 on 2023-05-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_cuser_datefrom_alter_cuser_dateto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='phone',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
